# APP
DEBUG: False
IP: 127.0.0.1
DOMAIN: "http://sabaccend.samuelanes.com:8080"
CROSS_ORIGIN: "https://225f86e9.sabacc.pages.dev"
PORT: 5000
DATABASE: "host=localhost port=5432 dbname=sabacc user=postgres password=postgres"